### ISSUE TITLE
Can't create Pantheon app

### ISSUE THREAD

**Issue by johnnypea** [kalabox/kalabox-app-pantheon#81]
Looks like it has some problem with initializing "CLI" container...
```
Pulling cli (kalabox/cli:dev)...
info: DOCKER-COMPOSE =>  dev: Pulling from kalabox/cli
info: DOCKER-COMPOSE =>  Digest: sha256:a72a11b4e5fbb46c2533f31b0b9db1fa63291b91b6b0080423f41da06f16765c
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/cli:dev
Creating myapp_cli_1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/compose/cli/main.py", line 54, in main
  File "/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/compose/compose/cli/docopt_command.py", line 26, in dispatch
  File "/compose/compose/cli/main.py", line 171, in perform_command
  File "/compose/compose/cli/main.py", line 546, in up
  File "/compose/compose/project.py", line 264, in up
  File "/compose/compose/service.py", line 389, in execute_convergence_plan
  File "/compose/compose/service.py", line 300, in create_container
  File "/compose/compose/container.py", line 46, in create
  File "/compose/venv/lib/python2.7/site-packages/docker/api/container.py", line 114, in create_container
  File "/compose/venv/lib/python2.7/site-packages/docker/api/container.py", line 119, in create_container_config
  File "/compose/venv/lib/python2.7/site-packages/docker/utils/utils.py", line 693, in create_container_config
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
docker-compose returned -1
info: DOCKER-COMPOSE =>  Run exited with code: 255
```

Kalabox v0.11

OS X 10.11.3

**Comment by pirog** [comment]
This error seems to be coming from docker compose. seems like there is a decent amount of activity on similar errors over there. 
https://github.com/docker/compose/issues/1314

**Comment by pirog** [comment]
@johnnypea i would also post this in the core kalabox issue repo over at github.com/kalabox/kalabox so we dont lose track of this

**Comment by johnnypea** [comment]
@pirog sure!

**Comment by pirog** [comment]
thx @johnnypea!
